// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cpack.proto

package class

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ContentPackDep struct {
	PackageId            string   `protobuf:"bytes,1,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	PackageVersion       string   `protobuf:"bytes,2,opt,name=package_version,json=packageVersion,proto3" json:"package_version,omitempty"`
	PackageName          string   `protobuf:"bytes,3,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	PackageDescription   string   `protobuf:"bytes,4,opt,name=package_description,json=packageDescription,proto3" json:"package_description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContentPackDep) Reset()         { *m = ContentPackDep{} }
func (m *ContentPackDep) String() string { return proto.CompactTextString(m) }
func (*ContentPackDep) ProtoMessage()    {}
func (*ContentPackDep) Descriptor() ([]byte, []int) {
	return fileDescriptor_e325fcb9aa346ca4, []int{0}
}

func (m *ContentPackDep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContentPackDep.Unmarshal(m, b)
}
func (m *ContentPackDep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContentPackDep.Marshal(b, m, deterministic)
}
func (m *ContentPackDep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContentPackDep.Merge(m, src)
}
func (m *ContentPackDep) XXX_Size() int {
	return xxx_messageInfo_ContentPackDep.Size(m)
}
func (m *ContentPackDep) XXX_DiscardUnknown() {
	xxx_messageInfo_ContentPackDep.DiscardUnknown(m)
}

var xxx_messageInfo_ContentPackDep proto.InternalMessageInfo

func (m *ContentPackDep) GetPackageId() string {
	if m != nil {
		return m.PackageId
	}
	return ""
}

func (m *ContentPackDep) GetPackageVersion() string {
	if m != nil {
		return m.PackageVersion
	}
	return ""
}

func (m *ContentPackDep) GetPackageName() string {
	if m != nil {
		return m.PackageName
	}
	return ""
}

func (m *ContentPackDep) GetPackageDescription() string {
	if m != nil {
		return m.PackageDescription
	}
	return ""
}

type ContentPack struct {
	ProjectId      string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ProjectName    string `protobuf:"bytes,2,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	ProjectVersion string `protobuf:"bytes,3,opt,name=project_version,json=projectVersion,proto3" json:"project_version,omitempty"`
	AuthorName     string `protobuf:"bytes,4,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`
	Synopsis       string `protobuf:"bytes,5,opt,name=synopsis,proto3" json:"synopsis,omitempty"`
	HasStory       bool   `protobuf:"varint,6,opt,name=has_story,json=hasStory,proto3" json:"has_story,omitempty"`
	// 7?
	ReadOnly     bool   `protobuf:"varint,8,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	PreviewImage string `protobuf:"bytes,9,opt,name=preview_image,json=previewImage,proto3" json:"preview_image,omitempty"`
	// float version, eh?
	GameVersionRequired     float32           `protobuf:"fixed32,10,opt,name=game_version_required,json=gameVersionRequired,proto3" json:"game_version_required,omitempty"`
	ContentPackDependencies []*ContentPackDep `protobuf:"bytes,20,rep,name=content_pack_dependencies,json=contentPackDependencies,proto3" json:"content_pack_dependencies,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}          `json:"-"`
	XXX_unrecognized        []byte            `json:"-"`
	XXX_sizecache           int32             `json:"-"`
}

func (m *ContentPack) Reset()         { *m = ContentPack{} }
func (m *ContentPack) String() string { return proto.CompactTextString(m) }
func (*ContentPack) ProtoMessage()    {}
func (*ContentPack) Descriptor() ([]byte, []int) {
	return fileDescriptor_e325fcb9aa346ca4, []int{1}
}

func (m *ContentPack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContentPack.Unmarshal(m, b)
}
func (m *ContentPack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContentPack.Marshal(b, m, deterministic)
}
func (m *ContentPack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContentPack.Merge(m, src)
}
func (m *ContentPack) XXX_Size() int {
	return xxx_messageInfo_ContentPack.Size(m)
}
func (m *ContentPack) XXX_DiscardUnknown() {
	xxx_messageInfo_ContentPack.DiscardUnknown(m)
}

var xxx_messageInfo_ContentPack proto.InternalMessageInfo

func (m *ContentPack) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *ContentPack) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *ContentPack) GetProjectVersion() string {
	if m != nil {
		return m.ProjectVersion
	}
	return ""
}

func (m *ContentPack) GetAuthorName() string {
	if m != nil {
		return m.AuthorName
	}
	return ""
}

func (m *ContentPack) GetSynopsis() string {
	if m != nil {
		return m.Synopsis
	}
	return ""
}

func (m *ContentPack) GetHasStory() bool {
	if m != nil {
		return m.HasStory
	}
	return false
}

func (m *ContentPack) GetReadOnly() bool {
	if m != nil {
		return m.ReadOnly
	}
	return false
}

func (m *ContentPack) GetPreviewImage() string {
	if m != nil {
		return m.PreviewImage
	}
	return ""
}

func (m *ContentPack) GetGameVersionRequired() float32 {
	if m != nil {
		return m.GameVersionRequired
	}
	return 0
}

func (m *ContentPack) GetContentPackDependencies() []*ContentPackDep {
	if m != nil {
		return m.ContentPackDependencies
	}
	return nil
}

func init() {
	proto.RegisterType((*ContentPackDep)(nil), "class.ContentPackDep")
	proto.RegisterType((*ContentPack)(nil), "class.ContentPack")
}

func init() { proto.RegisterFile("cpack.proto", fileDescriptor_e325fcb9aa346ca4) }

var fileDescriptor_e325fcb9aa346ca4 = []byte{
	// 364 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x92, 0x4d, 0xee, 0xd3, 0x30,
	0x10, 0xc5, 0x95, 0x86, 0x7f, 0x95, 0x4c, 0x4a, 0x91, 0x5c, 0x2a, 0x0c, 0x08, 0x11, 0xca, 0x82,
	0xac, 0x8a, 0x54, 0x8e, 0x40, 0x37, 0xdd, 0xf0, 0x11, 0x24, 0xb6, 0x91, 0xb1, 0x47, 0xad, 0x69,
	0x63, 0x07, 0x3b, 0x2d, 0xca, 0x59, 0xb8, 0x02, 0x87, 0x44, 0xfe, 0x48, 0x69, 0x97, 0xf3, 0x7b,
	0x2f, 0xa3, 0xf7, 0x9c, 0x81, 0x82, 0x77, 0x8c, 0x1f, 0xd7, 0x9d, 0xd1, 0xbd, 0x26, 0x0f, 0xfc,
	0xc4, 0xac, 0x5d, 0xfd, 0x4d, 0x60, 0xfe, 0x51, 0xab, 0x1e, 0x55, 0xff, 0x85, 0xf1, 0xe3, 0x16,
	0x3b, 0xf2, 0x0a, 0xc0, 0xf9, 0xd8, 0x1e, 0x1b, 0x29, 0x68, 0x52, 0x26, 0x55, 0x5e, 0xe7, 0x91,
	0xec, 0x04, 0x79, 0x07, 0x4f, 0x46, 0xf9, 0x82, 0xc6, 0x4a, 0xad, 0xe8, 0xc4, 0x7b, 0xe6, 0x11,
	0x7f, 0x0f, 0x94, 0xbc, 0x81, 0xd9, 0x68, 0x54, 0xac, 0x45, 0x9a, 0x7a, 0x57, 0x11, 0xd9, 0x27,
	0xd6, 0x22, 0x79, 0x0f, 0x8b, 0xd1, 0x22, 0xd0, 0x72, 0x23, 0xbb, 0xde, 0xed, 0x7b, 0xe4, 0x9d,
	0x24, 0x4a, 0xdb, 0xff, 0xca, 0xea, 0x4f, 0x0a, 0xc5, 0x4d, 0x5c, 0x9f, 0xd5, 0xe8, 0x9f, 0xc8,
	0xfb, 0xdb, 0xac, 0x81, 0xec, 0x84, 0x8f, 0x10, 0x65, 0x1f, 0x61, 0x12, 0x23, 0x04, 0xe6, 0x23,
	0xb8, 0x3a, 0xd1, 0x32, 0xd6, 0x49, 0x63, 0x9d, 0x80, 0xc7, 0x3a, 0xaf, 0xa1, 0x60, 0xe7, 0xfe,
	0xa0, 0x4d, 0x58, 0x15, 0x32, 0x42, 0x40, 0x7e, 0xd3, 0x0b, 0xc8, 0xec, 0xa0, 0x74, 0x67, 0xa5,
	0xa5, 0x0f, 0x5e, 0xbd, 0xce, 0xe4, 0x25, 0xe4, 0x07, 0x66, 0x1b, 0xdb, 0x6b, 0x33, 0xd0, 0x69,
	0x99, 0x54, 0x59, 0x9d, 0x1d, 0x98, 0xfd, 0xe6, 0x66, 0x27, 0x1a, 0x64, 0xa2, 0xd1, 0xea, 0x34,
	0xd0, 0x2c, 0x88, 0x0e, 0x7c, 0x56, 0xa7, 0x81, 0xbc, 0x85, 0xc7, 0x9d, 0xc1, 0x8b, 0xc4, 0xdf,
	0x8d, 0x6c, 0xd9, 0x1e, 0x69, 0xee, 0x57, 0xcf, 0x22, 0xdc, 0x39, 0x46, 0x36, 0xb0, 0xdc, 0xb3,
	0xf6, 0xfa, 0x43, 0x1a, 0x83, 0xbf, 0xce, 0xd2, 0xa0, 0xa0, 0x50, 0x26, 0xd5, 0xa4, 0x5e, 0x38,
	0x31, 0xf6, 0xa8, 0xa3, 0x44, 0xbe, 0xc2, 0x73, 0x1e, 0x5e, 0xb2, 0x71, 0x0f, 0xdd, 0x08, 0xec,
	0x50, 0x09, 0x54, 0x5c, 0xa2, 0xa5, 0x4f, 0xcb, 0xb4, 0x2a, 0x36, 0xcb, 0xb5, 0x3f, 0x92, 0xf5,
	0xfd, 0x81, 0xd4, 0xcf, 0xf8, 0xdd, 0x7c, 0xfd, 0xea, 0xc7, 0xd4, 0x9f, 0xd6, 0x87, 0x7f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x81, 0xe5, 0x86, 0xa4, 0x69, 0x02, 0x00, 0x00,
}
